### ISSUE TITLE
>> BLOCK BEGIN comments showing in admin on Edit entry pages

### ISSUE THREAD

**Issue by danystad** [nystudio107/craft-templatecomments#1]
Works great for templates.

However, the plugin adds the following comments above all field titles on Edit entry pages:

>> BLOCK BEGIN >> attr --> data-type="craft\fields\..." >

**Comment by khalwat** [comment]
Ah, it's because of the unescape quotes in there. Easy enough!

**Comment by khalwat** [comment]
I think I'm also going to disable it by default in the AdminCP. If you want to turn it on you can, but most people will probably want it off in the AdminCP.

**Comment by khalwat** [comment]
Fixed in 1.0.1 https://github.com/nystudio107/craft-templatecomments/releases/tag/1.0.1
