### ISSUE TITLE
When overwriting a block from a parent template - comments are getting printed into final result.

### ISSUE THREAD

**Issue by MichaelBrauner** [nystudio107/craft-templatecomments#25]
### Describe the bug
When extending a template `base.html.twig` :

```twig
<!DOCTYPE html>

<html lang="{{ craft.app.language }}">

<head>
    <title>{% block title %}{{ siteName }}{% endblock %}</title>
</head>
```

And try to change the title: 

```twig
{% extends 'base.html.twig' %}

{% if entry %}
     {% block title %} {{ entry.title }} {% endblock %}
{% endif %}
```

Comments are printed into final result: 

```html
<title>
&lt;!-- &gt;&gt;&gt; BLOCK BEGIN &gt;&gt;&gt; title --&gt;
 Kontakt 
&lt;!-- 0.01ms &lt;&lt;&lt; BLOCK END &lt;&lt;&lt; title --&gt;
</title>

```

### Expected behaviour
No comments should be printed into final result.

### Versions
- Plugin version: 1.1.2
- Craft version: ^3.6.4

**Comment by khalwat** [comment]
There is a block present, though, I'd expect that there would be comments output to indicate that block?

Can you help me understand why you believe this is a bug?

**Comment by MichaelBrauner** [comment]
Ah, I understand now.  I have to write the title tag inside the block - otherwise the comments are landing inside of the page title. 

Sorry for that. I love your work and your blogposts.

Cheers!

**Comment by KatieMFritz** [comment]
Hi Andrew! I'm running into this, and I agree that it's expected behavior, but I don't want it. I tried adding `title` to use the `excludeBlocksThatContain` setting, but no luck. Is that because the block itself is called `title`, but it doesn't _contain_ the word `title`?

**Comment by khalwat** [comment]
Use the `excludeBlocksThatContain` config setting @KatieMFritz :

https://github.com/nystudio107/craft-templatecomments/blob/develop/src/config.php#L44

If should work if the block is or contains `title` -- what version of the plugins are you using? Note: You might have to clear template caches after changing this setting, for it to apply to your compiled templates.
