### ISSUE TITLE
[FR] Add support for {% include %} back into the plugin

### ISSUE THREAD

**Issue by CreateSean** [nystudio107/craft-templatecomments#40]
### Describe the bug

Template comments is not working with matrix blocks in new versions

![image](https://user-images.githubusercontent.com/6899490/170105955-bbac574c-a42b-468c-84ae-9b93afbd352d.png)

In the screenshot the **circled sections** are each a matrix block but template comments is not telling me where they are located.

---

However in a **different older site** running Craft 3.7.37 and Template Comments 1.1.2 matrix blocks output comments as expected. See below.
![image](https://user-images.githubusercontent.com/6899490/170106680-643f92fc-f835-4464-bbbe-6e0592e9fe61.png)

### To reproduce
Steps to reproduce the behaviour:
1. Go to "..."
2. Click on "..."
3. See error message "..."

### Versions
- Plugin version: 1.2.0
- Craft version: 3.7.42

**Comment by khalwat** [comment]
Not exactly a bug, but not something you're likely to be happy about... due to compatibility with Twig 3 reasons, I removed the template loader shim that allowed those template delimiters.

You can still pin it to the older version of the plugin for Craft 3 if you want to keep that functionality. Maybe I'll figure out a better way to do it going forward.

Here's a good description from @MangoMarcus https://github.com/nystudio107/craft-templatecomments/issues/43

### Question
Is there no support for comments when using `{% include %}` ?

This plugin works well for `{% block %}` but the description to me implies it would cover using {% include %}

> Adds a HTML comment to demarcate each Twig template that is ***included*** or extended.

eg. using `{% include '_foo/my-template' %}` I'd expect something like
```html
<!-- >>> INCLUDE BEGIN >>> _foo/my-template FROM _foo/other-template -->
<!-- * template output here * -->
<!-- <<< INCLUDE END <<< _foo/my-template FROM _foo/other-template TIME 1.23ms -->
```

Thanks!

**Comment by CreateSean** [comment]
Oh... :( 

so this is removed in the Craft 4 compatible version, right? What is the most recent version that still has the delimiters? I'll lock to that in my C3 projects.

I'll wait until you figure out the better approach. Love this plugin alot.

**Comment by khalwat** [comment]
The Craft 4 / Twig 3 version does not log comments for `{% include %}`s -- but rather only `{% block %}`s (but those now include the template they are coming from).

The latest version of the Craft 3 plugin is at feature parity with the Craft 4 version, which means you lose the `{% include %}` comments. If you want to lock in the Craft 3 version that _does_ add `{% include %}` comments, set your semver to `1.1.2`.

No ETA on adding this functionality back into the Craft 4 version of the plugin; it'll have to wait until work settles down a bit on the other plugins.

**Comment by johnwbaxter** [comment]
I just came here to report this bug! This was what I used this plugin for, for looking at which block from my content builder was doing what and where :)

Really hope it comes back soon! Thanks Andrew!! :)

**Comment by taya13** [comment]
Indeed I was also using this plugin for generating comments for includes...
I also hope it will come back soon

**Comment by khalwat** [comment]
Same as https://github.com/nystudio107/craft-templatecomments/issues/43

**Comment by khalwat** [comment]
So I got this working for Craft 4 (really, for Twig 3.0)... and man it's ugly. But it works.

I'm going to think about it for a bit to see if there are better approaches

**Comment by khalwat** [comment]
Here's the commit in question: https://github.com/nystudio107/craft-templatecomments/commit/3b6b991cc81fb465d51a8542cfebece1504678db

...with a detailed explanation of the problem here: https://github.com/nystudio107/craft-templatecomments/blob/develop-v4/src/web/twig/TemplateCommentsParser.php#L11

**Comment by khalwat** [comment]
`1.2.1`, `4.0.1`, & `5.0.0` released with this FR added
