### ISSUE TITLE
[FR] Add support for {% include %} back into the plugin

### ISSUE THREAD

**Issue by MangoMarcus** [nystudio107/craft-templatecomments#43]
### Question
Is there no support for comments when using `{% include %}` ?

This plugin works well for `{% block %}` but the description to me implies it would cover using {% include %}

> Adds a HTML comment to demarcate each Twig template that is ***included*** or extended.

eg. using `{% include '_foo/my-template' %}` I'd expect something like
```html
<!-- >>> INCLUDE BEGIN >>> _foo/my-template FROM _foo/other-template -->
<!-- * template output here * -->
<!-- <<< INCLUDE END <<< _foo/my-template FROM _foo/other-template TIME 1.23ms -->
```

Thanks!

**Comment by khalwat** [comment]
It used to do this, but I removed the feature when I updated it for Craft 4. I can leave this open as a FR to bring it back if you like?

**Comment by MangoMarcus** [comment]
That'd be great thank you

**Comment by khalwat** [comment]
Same as https://github.com/nystudio107/craft-templatecomments/issues/40

**Comment by khalwat** [comment]
`1.2.1`, `4.0.1`, & `5.0.0` released with this FR added
